infovisproject1/infovisproject1/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('library.urls',namespace='library')),
]

infovisproject1/library/urls.py
from django.urls import path

from . import views

app_name = "library"

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.search_result, name='search_result'),
    path('document-details/<str:olid>/', views.document_details, name='details'),
    path('test-api-call/', views.my_django_view, name='my_django_view'),
    path('get-subject-matches/', views.get_subject_match_data, name='get_subject_match_data'),
    path('get-my-viewings/', views.get_my_subject_viewings, name='get_my_subject_viewings'),
]

infovisproject1/library/models.py
from django.db import models


class Subjects(models.Model):
    subject_text = models.CharField(max_length=200)
    hit_count = models.IntegerField(default=0)

infovisproject1/library/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.core import serializers
from django.http import JsonResponse
import requests
import json
import copy
# Create your views here.
from library.models import Subjects


def get_books_of_subjects(subject):
    response = requests.get('http://openlibrary.org/search.json?q=' + subject + '&limit=9')
    if response.status_code == 200:
        json_response = response.json()
        books = json_response['docs']
        return [books,int(json_response['numFound'])]
    return []


def index(request):
    # post = Post.objects.filter(status='published')
    template = 'index.html'
    romance_books,numbers_r = get_books_of_subjects("romance")
    thriller_books,numbers_t = get_books_of_subjects("thriller");
    arts_books,numbers_a = get_books_of_subjects("arts");
    r_num_str = ""
    if numbers_r == 0:
        r_num_str = "0"
    elif numbers_r < 1000:
        r_num_str = "1k"
    else:
        r_num_str = str(float("{:.2f}".format(numbers_r/1000))) + "k"

    t_num_str = ""
    if numbers_t == 0:
        t_num_str = "0"
    elif numbers_t < 1000:
        t_num_str = "1k"
    else:
        t_num_str = str(float("{:.2f}".format(numbers_t/1000))) + "k"

    a_num_str = ""
    if numbers_a == 0:
        a_num_str = "0"
    elif numbers_a < 1000:
        a_num_str = "1k"
    else:
        a_num_str = str(float("{:.2f}".format(numbers_a/1000))) + "k"
    context = {
        "romance_books" : romance_books,
        "thriller_books": thriller_books,
        "arts_books"    : arts_books,
        "romance_book_count": r_num_str,
        "thriller_book_count": t_num_str,
        "arts_book_count": a_num_str
    }
    # print(romance_books)
    return render(request, template, context)
    # return HttpResponse("Hello, world. You're at the polls index.")

def my_django_view(request):
    # for key in request.POST:
    #     print(key)
    # print(request.POST)
    # document = request.POST['document_item']
    # doc_json = json.loads(document)
    # subjects = doc_json['subject']
    # print(subjects)
    # a = ['romance','love']
    # results = Subjects.objects.filter(subject_text__iregex=r'(' + '|'.join(subjects) + ')').order_by('-hit_count')
    # context_data = []
    # for result in results:
    #     data = { 'name' : result.subject_text, 'hits': result.hit_count}
    #     context_data.append(data)
    #
    # print(type(result))
    # return JsonResponse(data, safe=False)
    if request.method == 'GET':
        response = requests.get('http://openlibrary.org/subjects/romance.json?limit=5', params=request.GET)
    # else:
    #     r = requests.get('https://www.somedomain.com/some/url/save', params=request.GET)
    if response.status_code == 200:
        response2= response.json()
        key= response2['key']
        return HttpResponse(str(key))
    return HttpResponse('Could not save data'+str(response.status_code))

def search_result(request):
    # post = Post.objects.filter(status='published')
    template = 'search-results-page-basic.html'
    keywords = request.GET['keywords']
    keyword_with_plus = keywords.replace(" ","+")
    keywords_with_space = keywords
    current_page_number = int(request.GET['pagenum'])
    offset = (current_page_number - 1 )*10
    query = 'http://openlibrary.org/search.json?q='+ keyword_with_plus+'&&limit=10'
    if offset !=0:
        query = query + '&&offset=' + str(offset)
    response = requests.get(query)
    response2 = response.json()
    documents = response2['docs']
    # print(request.GET)

    # print(keywords_with_space)
    # romance_books = get_books_of_subjects("romance")
    # thriller_books = get_books_of_subjects("thriller");
    # arts_books = get_books_of_subjects("arts");
    context = {
        "searched_keywords": keywords_with_space,
        "searched_keywords_with_plus": keyword_with_plus,
        "documents"        : documents,
        "existing_page_num": current_page_number,
        "number_of_results": response2['numFound']
        # "romance_books" : romance_books,
        # "thriller_books": thriller_books,
        # "arts_books"    : arts_books
    }
    return render(request, template, context)
def document_details(request, olid):
    template = 'document_details_page_basic.html'
    # document_olid = olid
    # query = 'https://openlibrary.org/api/books?bibkeys=OLID:' + document_olid + '&jscmd=data&format=json'
    # r = requests.get(query)
    # response = r.json()
    # document = response['OLID:'+document_olid]
    context = {

    }
    return render(request, template, context)

def get_subject_match_data(request):
    document = request.POST['document_item']
    doc_json = json.loads(document)
    context_data = []
    if 'subject' in doc_json and len(doc_json['subject']):
        subjects = doc_json['subject']
        print(subjects)
        # a = ['romance', 'love']
        results = Subjects.objects.filter(subject_text__iregex=r'(' + '|'.join(subjects) + ')').order_by('-hit_count')[:10]

        for result in results:
            # print("loop iteration")
            data = {'name': result.subject_text, 'hits': result.hit_count}
            context_data.append(data)

        #now updating existing results
        for subject in subjects:
            result_matches = Subjects.objects.filter(subject_text__iregex=r'('+subject+')')
            if result_matches:
                for match in result_matches:
                    count = match.hit_count+1
                    match.hit_count = count
                    match.save()
            else:
                new_subject = Subjects(subject_text=subject, hit_count=1)
                new_subject.save()
            # MyModel.objects.filter(pk=some_value).update(field1='some value')
    return JsonResponse(context_data, safe=False)

def get_my_subject_viewings(request):
    template = 'my_reading_patterns.html'
    results = Subjects.objects.all().order_by('-hit_count')[:10]
    # document_olid = olid
    # query = 'https://openlibrary.org/api/books?bibkeys=OLID:' + document_olid + '&jscmd=data&format=json'
    # r = requests.get(query)
    # response = r.json()
    # document = response['OLID:'+document_olid]
    context_data = []
    for result in results:
        # print("loop iteration")
        data = {'name': result.subject_text, 'hits': result.hit_count}
        context_data.append(data)
    context = {
        "reading_data": context_data
    }
    return render(request, template, context)

infovisproject1/library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    {% block title %}
        <!-- When extending this base page, write title of the page in this block -->
    {% endblock %}



    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'slick/slick.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'slick/slick-theme.css' %}"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.1/css/all.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/overall-style.css' %}"/>

    <!-- Custom styles for this template -->
    <link href="{% static 'css/heroic-features.css' %}" rel="stylesheet">
    {#<link rel="stylesheet" type="text/css" href="{% static 'css/overall-style.css' %}"/>#}
    {% block css %}
        <!-- Include page specific styles here -->
    {% endblock %}


</head>

<body>

<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="#">Link</a>#}
{#                </li>#}
{#                <li class="nav-item dropdown">#}
{#                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"#}
{#                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">#}
{#                        Dropdown#}
{#                    </a>#}
{#                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">#}
{#                        <a class="dropdown-item" href="#">Action</a>#}
{#                        <a class="dropdown-item" href="#">Another action</a>#}
{#                        <div class="dropdown-divider"></div>#}
{#                        <a class="dropdown-item" href="#">Something else here</a>#}
{#                    </div>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link disabled" href="#">Disabled</a>#}
{#                </li>#}
            </ul>
            <form class="form-inline my-2 my-lg-0" action="{% url 'library:search_result' %}" method="get">

                {#      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style="min-width: 400px">#}
                <div class="input-group">
{#                    <div class="input-group-prepend">#}
{#                        <button class="btn btn-light dropdown-toggle border-right" type="button" data-toggle="dropdown"#}
{#                                aria-haspopup="true" aria-expanded="false" id="AdvancedSearch"><span class="selection">All</span>#}
{#                        </button>#}
{#                        <div class="dropdown-menu" id="saerch-dropdown-id">#}
{#                            <a class="dropdown-item" href="#">All</a>#}
{#                            <div role="separator" class="dropdown-divider"></div>#}
{#                            <a class="dropdown-item" href="#">Keywords</a>#}
{#                            <a class="dropdown-item" href="#">Subjects</a>#}
{#                                                        <a class="dropdown-item" href="#">Something else here</a>#}
{#                                                        <div role="separator" class="dropdown-divider"></div>#}
{#                                                        <a class="dropdown-item" href="#">Separated link</a>#}
{#                        </div>#}
{#                    </div>#}
                    {% if searched_keywords %}
                        <input type="text" name="keywords" class="form-control" id="searchfield"
                               aria-label="Text input with dropdown button" value="{{ searched_keywords }}">
                    {% else %}
                        <input type="text" name="keywords" class="form-control" id="searchfield" placeholder="Enter your query here"
                               aria-label="Text input with dropdown button">
                    {% endif %}


                    <input type="hidden" name="pagenum" class="form-control" id="searchfield"
                               aria-label="Text input with dropdown button" value="{{ 1 }}">

                    <div class="input-group-append">
                        <button class="btn btn-light border-left" type="submit"><em class="fa fa-search"><a
                                href=></a></em></button>
                    </div>
                </div>

            </form>
        </div>

    </div>
</nav>

<!-- Page Content -->
<div class="container">
    {% block content %}
        <!-- Extend this base template and add the page content here -->
    {% endblock %}


</div>
<!-- /.container -->

<!-- Footer -->
<footer class="py-5 bg-dark">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; Your Website 2020</p>
    </div>
    <!-- /.container -->
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<script type="text/javascript" src="{% static 'slick/slick.min.js' %}"></script>
{% block js %}
    <!-- When extending this base template, then write page specific js codes in this block -->
{% endblock %}


</body>

</html>

infovisproject1/library/templates/my_reading_patterns.html
{% extends 'base.html' %}
{% load static %}
{% load range %}

{% block title %}
    <title>Home</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/list-page-style.css' %}"/>


{% endblock %}

{% block content %}

    <h4>My top viewings of subjects by view numbers</h4>
    <svg width="1500" height="500" id="graphsvgid"></svg>

{% endblock %}

{% block js %}
    <script src="{% static 'js/d3.v3.min.js' %}"></script>
    <script src="{% static 'js/d3.tip.v0.6.3.js' %}"></script>
    {{ reading_data|json_script:"classdata" }}
    <script>
        const reading_data_json = JSON.parse(document.getElementById('classdata').textContent);
        var margin = {top: 40, right: 20, bottom: 30, left: 70},
            width = 1500 - margin.left - margin.right,
            height = 500 - margin.top - margin.bottom;

        var data = reading_data_json
        //[{"Employee": "John Doe", "Salary": 58}, {
        //"Employee": "Jane Doe",
        //  "Salary": 81
        // }, {"Employee": "Mary Jane", "Salary": 39}, {
        //     "Employee": "Debasis Das",
        //     "Salary": 80
        // }, {"Employee": "Nishant Singh", "Salary": 99}];

        var x = d3.scale.ordinal()
            .rangeRoundBands([0, width / 1.5], .1);

        var y = d3.scale.linear()
            .range([height, 0]);

        var xAxis = d3.svg.axis()
            .scale(x)
            .orient("bottom");

        var yAxis = d3.svg.axis()
            .scale(y)
            .orient("left")
            .ticks(10, "");

        var tip = d3.tip()
            .attr('class', 'd3-tip')
            .offset([-10, 0])
            .html(function (d) {
                return "<strong>Viewed document of this subject:</strong> <span style='color:red'>" + d.hits + "</span>";
            })
        var svg = d3.select("svg")
            .attr("width", width + margin.left + margin.right)
            .attr("height", height + margin.top + margin.bottom)
            .append("g")
            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");

        svg.call(tip);


        x.domain(data.map(function (d) {
            return d.name;
        }));
        y.domain([0, d3.max(data, function (d) {
            return d.hits;
        })]);

        svg.append("g")
            .attr("class", "x axis")
            .attr("transform", "translate(20," + height + ")")
            .call(xAxis)
            .attr("font-size", "13px")
        {#.append("text")#}
        {#.attr("class", "axis-title")#}
        {#.attr("y", 28)#}
        {#.attr("dy", ".05em")#}
        {##}
        {#.text("Subjects ->")#}
        {#.attr("font-size", "13px");;#}

        svg.append("g")
            .attr("class", "y axis")
            .call(yAxis)
            .append("text")
            .attr("transform", "rotate(-90)")
            .attr("y", -36)
            .attr("dy", ".71em")
            .style("text-anchor", "end")
            .text("Number of documents viewed")
            .attr("font-size", "13px");


        svg.selectAll(".bar")
            .data(data)
            .enter().append("rect")
            .attr("class", "bar")
            .attr("x", function (d) {
                return x(d.name);
            })
            .attr("width", x.rangeBand())
            .attr("y", function (d) {
                return y(d.hits);
            })
            .attr("height", function (d) {
                return height - y(d.hits);
            })
            .on('mouseover', tip.show)
            .on('mouseout', tip.hide);


        function type(d) {
            d.Salary = +d.Salary;
            return d;
        }
    </script>
{% endblock %}

infovisproject1/library/templates/search-results-page-basic.html
{% extends 'base.html' %}
{% load static %}
{% load range %}

{% block title %}
    <title>Home</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/list-page-style.css' %}"/>


{% endblock %}

{% block content %}

    <!-- Page Features -->

    <p> Total number of <b>{{ number_of_results }} </b> documents found with the keyword</p>

    <div class="card p-3" id="card_body_id">
        {% for document in documents %}
            <div class="card mb-3">
            <div class="flex-column">
            <div class="row no-gutters">
                   <div class="col-md-2">
                        {% if document.cover_i %}
                            <img src="http://covers.openlibrary.org/b/id/{{ document.cover_i }}-M.jpg"
                                 class="card-img-top"
                                 alt="image not found">
                        {% else %}
                            <img src="{% static 'images/image-not-found-1024x576.png' %}" class="card-img-top"
                                 alt="image not found">
                        {% endif %}
                    </div>
                <div class="col-md-9">
                        <div class="card-body">
                            <a class="url-event" href="{% url 'library:details' document.seed.0|to_and %}"><h5
                                    class="card-title">{{ document.title }}</h5></a>
{#                            {{ document.seed.0 }}#}
                            <p class="card-text">This is a book about {{ document.title }}. Further details are not
                            found from the server at the moment.</p>
                            <p class="card-text"><small class="text-muted">Last updated <u> {% random_int 10 50 %} </u> mins ago</small></p>
                        </div>
                    </div>
                <div class="card-footer col-md-1" style="float: right;text-align: center">
                                {#                            <a href="#" class="btn btn-primary">Find Out More!</a>#}
                                <div class="flex-column">
                                    <div class="col-sm-12 p-0 border-bottom"><i class="fa fa-tablet" aria-hidden="true"></i>
                                        <br>Ebook
                                    </div>
                                    <div class="col-sm-12 p-0 border-bottom">{% random_float 3.5 5 %} <i class="fa fa-star" aria-hidden="true"></i>
                                        <br> Ratings
                                    </div>
                                    <div class="col-sm-12 p-0"><b>{% random_int 3 10 %}k</b><br>Borrowings</div>

                                </div>
                </div>


            </div>
            <div class="accordion" id="accordionExample">
                    <div class="card">
                        <div class="" id="headingTwo">
                            <h2 class="mb-0">

                                {% if document.subject %}
                                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse"
                                            data-target="#collapseTwo{{ document.first_publish_year }}"
                                            aria-expanded="false" aria-controls="collapseTwo">
                                    Subjects in this document ({{ document.subject|length }})
                                {% else %}
                                    <button class="btn collapsed" type="button" data-toggle="collapse"
                                            aria-expanded="false" aria-controls="collapseTwo">
                                    Subjects in this document (0)
                                {% endif %}


                                </button>
                            </h2>
                        </div>
                        <div id="collapseTwo{{ document.first_publish_year }}" class="collapse"
                             aria-labelledby="headingTwo"
                             data-parent="#accordionExample">
                            <div class="card-body">
                                <ul class="list-inline">
                                    {% for subject in document.subject %}
                                        <li>
                                            <a href="/search?keywords={{ subject.split|join:"+" }}&&pagenum=1">{{ subject }}</a>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </div>



        {% endfor %}

    </div>

    <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if existing_page_num %}
                {% if existing_page_num == 1 %}
                    <li class="page-item"><a class="page-link">Previous</a></li>
                {% elif  existing_page_num > 1 %}
                    <li class="page-item"><a class="page-link"
                                             href="?keywords={{ searched_keywords_with_plus }}&&pagenum={{ existing_page_num|add:"-1" }}">Previous</a>
                    </li>
                {% endif %}
                {% for i in 1|range:11 %}
                    {% if existing_page_num == i %}
                        <li class="page-item"><a class="page-link">{{ i }}</a></li>
                    {% else %}
                        <li class="page-item"><a class="page-link"
                                                 href="?keywords={{ searched_keywords_with_plus }}&&pagenum={{ i }}">{{ i }}</a>
                        </li>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <li class="page-item"><a class="page-link"
                                     href="?keywords={{ searched_keywords_with_plus }}&&pagenum={{ existing_page_num|add:"1" }}">Next</a>
            </li>
        </ul>
    </nav>

{% endblock %}
{% block js %}
    {{ documents|json_script:"classdata" }}
    <script>

        var elems = document.getElementsByClassName('url-event');
        for (var i = 0; i < elems.length; i++) {
            elems[i].addEventListener('click', function (event) {
                listener(event)
            }, false);
        }

        function listener(event) {
// Do something before following the link

            // Get url from the target element (<a>) href attribute
            {#var url = event.target.href;#}
            {#console.log(event)#}
            {#event.preventDefault();#}
            {#alert("Hi")#}
            var anchor = event.target.closest("a");     // Find closest Anchor (or self)
            console.log(anchor.getAttribute('href'));
            main_url = anchor.getAttribute('href')
            element_id = main_url.substring(18, main_url.length - 1);
            console.log("The id is " + element_id)
            const value = JSON.parse(document.getElementById('classdata').textContent);
            console.log(value)
            var i;
            var desired_document;
            for (i = 0; i < value.length; i++) {
                var item = value[i];
                console.log(item.seed[0]);
                let newStr = item.seed[0].replace("/books/", "");
                if (newStr == element_id) {
                    desired_document = item
                    break
                }
            }
            console.log(" the index is " + i)
            localStorage.setItem(element_id, JSON.stringify(desired_document));

            // Open the url in the current window. Set to "_blank" instead of "_self" to open in a new window.
            {#window.open(url, '_self');#}

            // Prevent default action (e.g. following the link)
        }
    </script>
{% endblock %}